name: Create new realease

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install fuse libfuse2
      run: sudo apt install fuse libfuse2

    - name: Make Calibre AppDir
      run: |
        set -x
        version=$(grep -o "Calibre:.*" README.md | cut -d ' ' -f2)
        echo "Calibre version: $version"

        #rm -rf calibre.AppDir/
        mkdir -p calibre.AppDir/

        #cp calibre.desktop calibre.AppDir/

        cat > calibre.AppDir/calibre.desktop << 'EOF'
        [Desktop Entry]
        Type=Application
        Name=Calibre
        Comment=E-Book Management
        Exec=calibre %F
        Icon=calibre
        MimeType=application/x-mobipocket-ebook;application/epub+zip;x-content/ebook-reader
        Categories=Office;Graphics;Viewer
        EOF

        chmod +x calibre.AppDir/calibre.desktop

        cat > calibre.AppDir/AppRun << 'EOF'
        #!/bin/bash
        HERE="$(dirname "$(readlink -f "${0}")")"

        cd /"$HERE"/usr/bin/
        ./calibre
        EOF

        #curl --location -o calibre.AppDir/AppRun https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64
        chmod +x calibre.AppDir/AppRun

        mkdir -p calibre.AppDir/usr/bin/
        cd calibre.AppDir/usr/bin/
        curl -o - https://download.calibre-ebook.com/$version/calibre-$version-x86_64.txz | tar -xJf -

        pwd
        ls -lah
        cd ../../../
        pwd
        ls -lah

        cp calibre.AppDir/usr/bin/resources/content-server/calibre.png calibre.AppDir
        cp README.md calibre.AppDir

    - name: Get appimagetool
      run: |
        set -x
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
        #wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage

        version_go_appimage=$(wget -q -O - https://api.github.com/repos/probonopd/go-appimage/releases | grep "\"name.*appimagetool-.*-x86_64.AppImage\"" | head -n 1 | cut -d '-' -f2)
        echo "version_go_appimage: $version_go_appimage"

        wget -q "https://github.com/probonopd/go-appimage/releases/download/continuous/appimagetool-$version_go_appimage-x86_64.AppImage" -O appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    - name: Make AppImage
      run:  |
        set -x
        pwd; ls -lah
        version=$(grep -o "Calibre:.*" README.md | cut -d ' ' -f2)
        echo "Calibre version: $version"

        ARCH=x86_64 VERSION="${version}-1_JB" ./appimagetool-x86_64.AppImage calibre.AppDir

        fileName=$(ls Calibre*.AppImage)
        echo "fileName: $fileName"

        md5sum "$fileName" > "${fileName}.md5"
        pwd; ls -lah

    # Build - Errror: Resource not accessible by integration
    # Change Settings -> Actions -> General -> Workflow Permissions to allow read and write:
    # https://github.com/actions/first-interaction/issues/10#issuecomment-1506118886

    # https://github.com/marketplace/actions/upload-to-github-release
    - uses: xresloader/upload-to-github-release@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "Calibre*.AppImage; Calibre*.zsync ; Calibre*.md5"
          #delete_file: "random-name-*.txt;random-*.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          #overwrite: true
          verbose: true
          #tags: true
          draft: false
          default_release_name: "Calibre V in AppImage"
